kind: Deployment
apiVersion: apps/v1
metadata:
  name: qdrant-deployment
  namespace: canchat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qdrant-deployment
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qdrant-data
        - name: snapshots
          persistentVolumeClaim:
            claimName: qdrant-snapshots
      containers:
        - name: container
          image: 'ca.icr.io/canchatapp/qdrant:07-25-24'
          ports:
            - containerPort: 6333
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
            - name: snapshots
              mountPath: /qdrant/snapshots
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
