apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: canchat-webui-pvc
  namespace: canchat-v2-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-b0dd9620-6e1b-4af4-9167-f9ac4d57ee7b
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem