apiVersion: v1
kind: Service
metadata:
  name: canchat-webui-service
  namespace: canchat-v2-dev
spec:
  clusterIP: 172.21.43.246
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.21.43.246
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: canchat-webui-deployment